### PR TITLE
chore: remove twitter from available login_providers

### PR DESCRIPTION
**Pull request by salzig**
I don't think we intend to reintegrate it, and it doesn't work right now. Lets remove it then?

### CODE REVIEW

**Comment by phoet** [comment]
Well, you can actually create a new app and allow twitter logins again. The old login tokens are all invalid though.

**Comment by salzig** [comment]
Is it still possible to get new accounts/clients? I thought twitter (now X) killed that feature for free users.

**Comment by phoet** [comment]
It should I created a new app for weg.li at one point.

**Comment by salzig** [comment]
Ok, will need to check that. Closing this.

**Pull request closed without merging**
